---
#####
# httpd.confのデプロイ
#####
- name: check existance /etc/httpd/conf
  stat: path=/etc/httpd/conf
  register: etc_httpd_conf

- name: deploy /etc/httpd/conf/httpd.conf
  template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  when: etc_httpd_conf.stat.exists

- name: rewirte /etc/httpd/conf/httpd.conf
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    state=present
    backrefs=yes
    regexp={{ item.regexp }}
    line={{ item.line }}
  with_items:
    - regexp: 'User apache'
      line: 'User vagrant'
    - regexp: 'Group apache'
      line: 'Group vagrant'
    - regexp: 'EnableSendfile on'
      line: 'EnableSendfile off'
  when:
    - env == "local"
    - etc_httpd_conf.stat.exists

- name: check existance /usr/local/apache2/conf
  stat: path=/usr/local/apache2/conf
  register: usr_local_apache_conf

- name: deploy /usr/local/apache2/conf/httpd.conf
  template: src=httpd.conf dest=/usr/local/apache2/conf/httpd.conf
  when: usr_local_apache_conf.stat.exists

- name: rewirte /usr/local/apache2/conf/httpd.conf
  lineinfile:
    dest=/usr/local/apache2/conf/httpd.conf
    state=present
    backrefs=yes
    regexp={{ item.regexp }}
    line={{ item.line }}
  with_items:
    - regexp: 'User apache'
      line: 'User vagrant'
    - regexp: 'Group apache'
      line: 'Group vagrant'
    - regexp: 'EnableSendfile on'
      line: 'EnableSendfile off'
  when:
    - env == "local"
    - usr_local_apache_conf.stat.exists

#####
# laravel.conf のデプロイ
#####
- name: check existance /etc/httpd/conf.d
  stat: path=/etc/httpd/conf.d
  register: etc_httpd_conf_d

- name: deploy /etc/httpd/conf.d/laravel.conf
  template: src=laravel.{{ env }}.conf dest=/etc/httpd/conf.d/laravel.conf
  when: etc_httpd_conf_d.stat.exists

- name: check existance /usr/local/apache2/conf.d
  stat: path=/usr/local/apache2/conf.d
  register: usr_local_httpd_conf_d

- name: deploy config
  template: src=laravel.{{ env }}.conf dest=/usr/local/apache2/conf.d/laravel.conf
  when: usr_local_httpd_conf_d.stat.exists


