---
- name: setup nodejs8.x
  become: yes
  shell: curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -
- name: installing latest version of node.js
  become: yes
  yum:
    name: nodejs
    state: latest

# - name: Check Node.js repository version
#   shell: yum info nodejs | grep -e "Version\s*:\s*[6-9].*$"
#   register: nodejs_repository_version
#   always_run: yes
#   changed_when: false
#   failed_when: false

# - name: Register Node.js repository
#   shell: curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
#   when: nodejs_repository_version.stdout == ""

# - name: Install the latest version of Node.js
#   yum: name=nodejs state=latest

- name: Install "executor" node.js package.
  npm:
    name: '@lassehaslev/executor'
    global: true

- name: Install "eslint" node.js package.
  npm:
    name: 'eslint'
    global: true

- name: Install "eslint-plugin-vue@next" node.js package.
  npm:
    name: 'eslint-plugin-vue@next'
    global: true

- name: Install "eslint-config-vue" node.js package.
  npm:
    name: 'eslint-config-vue'
    global: true

- name: put "tdd eslintrc"
  template: 'src=eslintrc.json dest={{ homedir }}/apps/myapp/.eslintrc.json'

- name: put "tdd eslintignore"
  template: 'src=eslintignore dest={{ homedir }}/apps/myapp/.eslintignore'

- name: put "tdd command"
  template: 'src=tdd dest={{ homedir }}/apps/myapp/tdd'

- name: chmod "tdd"
  command: 'chmod 755 {{ homedir }}/apps/myapp/tdd'

